<a href="https://colab.research.google.com/github/PranamAcharya10/Python-Programs/blob/main/strassen_mat_mult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def split(matrix):
    row, col = matrix.shape
    #int(row,col)
    row2, col2 = row//2, col//2
    #print(row2,col2)
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen(x, y):

	# Base case when size of matrices is 1x1
	if x.shape[0] == 1:
		return x * y

	# Splitting the matrices into quadrants. This will be done recursively
	# untill the base case is reached.
	a, b, c, d = split(x)
	e, f, g, h = split(y)

	# Computing the 7 products, recursively (p1, p2...p7)
	p1 = strassen(a, f - h)
	p2 = strassen(a + b, h)
	p3 = strassen(c + d, e)
	p4 = strassen(d, g - e)
	p5 = strassen(a + d, e + h)
	p6 = strassen(b - d, g + h)
	p7 = strassen(a - c, e + f)

	# Computing the values of the 4 quadrants of the final matrix c
	c11 = p5 + p4 - p2 + p6
	c12 = p1 + p2
	c21 = p3 + p4
	c22 = p1 + p5 - p3 - p7

	# Combining the 4 quadrants into a single matrix by stacking horizontally and vertically.
	c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))
	return c

In [ ]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))

print("Enter the entries in a single line (separated by space): ")
# User input of entries in a single line separated by space
entries_X = list(map(int, input().split()))

# For printing the matrix X
X = np.array(entries_X).reshape(R, C)
print(X)

print("Enter the entries in a single line (separated by space): ")
entries_Y= list(map(int, input().split()))

# For printing the matrix Y
Y = np.array(entries_Y).reshape(R, C)
print(Y)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 1 1
[[1 2]
 [1 1]]
Enter the entries in a single line (separated by space): 
2 1 1 1
[[2 1]
 [1 1]]


In [ ]:
strassen(X, Y)

array([[4, 3],
       [3, 2]])

In [ ]:
print(X)
print(Y)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
